[package]
name = "tartarus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Tokio Dependencies
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
axum = "0.6.20"
hyper = "0.14.27"
tower = "0.4.13"

bb8 = "0.8.1"
diesel = "2.1.3"
diesel-async = { version = "0.4.1", features = ["postgres", "bb8"] }

serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
josekit = "0.8.4"

thiserror = "1.0.49"
error-stack = "0.4.1"
futures-util = "0.3.28"

[dev-dependencies]
rand = "0.8.5"





[[bin]]
name = "locker"
