[package]
name = "tartarus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["kms", "middleware", "key_custodian"]
kms = ["dep:aws-config", "dep:aws-sdk-kms"]
middleware = []
key_custodian = []

[dependencies]
aws-config = { version = "0.55.3", optional = true }
aws-sdk-kms = { version = "0.28.0", optional = true }
base64 = "0.21.2"
futures = "0.3.28"
# Tokio Dependencies
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
axum = "0.6.20"
hyper = "0.14.27"
tower = "0.4.13"


diesel = { version = "2.1.3", features = ["postgres", "serde_json", "time"] }
diesel-async = { version = "0.4.1", features = ["postgres", "deadpool"] }

serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
josekit = "0.8.4"

thiserror = "1.0.49"
config = "0.13.3"
serde_path_to_error = "0.1.11"
error-stack = "0.4.1"
futures-util = "0.3.28"
digest = "0.9"
masking = { git = "https://github.com/juspay/hyperswitch", version = "0.1.0" }
ring = { version = "0.16.20", features = ["std"] }
hex = "0.4.3"
time = "0.3.30"
async-trait = "0.1.74"
uuid = { version = "1.5.0", features = [  "v4", "fast-rng"] }

[dev-dependencies]
rand = "0.8.5"
axum-test = "13.0.1"



[[bin]]
name = "locker"
